# Generated by Django 5.2.5 on 2025-09-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
