# Generated by Django 5.2.6 on 2025-09-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_staff', '0002_alter_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(default='staff', max_length=20),
        ),
    ]
