# Generated by Django 5.1.7 on 2025-09-25 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_franchise', '0004_addfranchise_user_alter_addfranchise_location_and_more'),
        ('add_staff', '0003_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='franchise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='add_franchise.addfranchise'),
        ),
    ]
