# Generated by Django 4.2.16 on 2025-09-24 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "add_franchise",
            "0004_addfranchise_user_alter_addfranchise_location_and_more",
        ),
        ("add_staff", "0003_alter_staff_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_type", models.CharField(default="staff", max_length=20)),
                ("person_id", models.IntegerField()),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Present", "Present"),
                            ("Absent", "Absent"),
                            ("Late", "Late"),
                            ("Excused", "Excused"),
                        ],
                        default="Present",
                        max_length=20,
                    ),
                ),
                ("in_time", models.TimeField(blank=True, null=True)),
                ("out_time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "franchise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="add_franchise.addfranchise",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "person_id"],
                "unique_together": {("franchise", "person_type", "person_id", "date")},
            },
        ),
    ]
