# Generated by Django 4.2.16 on 2025-09-24 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "add_franchise",
            "0004_addfranchise_user_alter_addfranchise_location_and_more",
        ),
        ("add_staff", "0004_attendancerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="franchise_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_members",
                to="add_franchise.addfranchise",
            ),
        ),
    ]
