# Generated by Django 4.2.16 on 2025-09-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("add_staff", "0005_staff_franchise_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="batch",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
