<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-09-21 10:24
=======
# Generated by Django 5.1.7 on 2025-09-20 12:08
>>>>>>> 0e4e6f2643de68422040e1c858d812192d5886c7

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD
    dependencies = [
        ("add_course", "0001_initial"),
=======

    dependencies = [
        ('add_course', '0001_initial'),
>>>>>>> 0e4e6f2643de68422040e1c858d812192d5886c7
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="course",
            name="students",
=======
            model_name='course',
            name='students',
>>>>>>> 0e4e6f2643de68422040e1c858d812192d5886c7
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
