# Generated by Django 5.2.5 on 2025-09-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("add_course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="students",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
