<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-09-22 10:53
=======
# Generated by Django 5.1.7 on 2025-09-22 11:33
>>>>>>> 9a69325f5d960ccb4c3f1a68cba36347984d2c4b

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD
    dependencies = [
        ("add_course", "0001_initial"),
=======

    dependencies = [
        ('add_course', '0001_initial'),
>>>>>>> 9a69325f5d960ccb4c3f1a68cba36347984d2c4b
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="course",
            name="students",
=======
            model_name='course',
            name='students',
>>>>>>> 9a69325f5d960ccb4c3f1a68cba36347984d2c4b
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
