# Generated by Django 5.1.7 on 2025-09-23 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_course', '0002_alter_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
