# Generated by Django 5.2.5 on 2025-08-30 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Franchise",
        ),
    ]
