# Generated by Django 5.2.5 on 2025-09-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("franchise_head", "Franchise Head"),
                    ("staff", "Staff"),
                ],
                default="admin",
                max_length=20,
            ),
        ),
    ]
