# Generated by Django 5.2.6 on 2025-09-19 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_franchise', '0004_addfranchise_user_alter_addfranchise_location_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='add_franchise.addfranchise'),
        ),
    ]
