# Generated by Django 5.1.7 on 2025-09-20 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_franchise', '0004_addfranchise_user_alter_addfranchise_location_and_more'),
        ('notifications', '0002_alter_notification_franchise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='add_franchise.addfranchise'),
        ),
    ]
