# Generated by Django 5.2.5 on 2025-09-22 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "add_franchise",
            "0004_addfranchise_user_alter_addfranchise_location_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("batch", models.CharField(max_length=50)),
                (
                    "feesPaid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "feesPending",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "franchise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="add_franchise.addfranchise",
                    ),
                ),
            ],
        ),
    ]
