# Generated by Django 5.2.5 on 2025-09-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("add_student", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
