# Generated by Django 5.2.5 on 2025-09-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("add_franchise", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="franchise",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="inactive",
                max_length=20,
            ),
        ),
    ]
