# Generated by Django 5.2.5 on 2025-09-01 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("add_franchise", "0002_alter_franchise_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Franchise",
            new_name="AddFranchise",
        ),
    ]
