# Generated by Django 5.2.5 on 2025-09-16 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("add_franchise", "0003_rename_franchise_addfranchise"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="addfranchise",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="franchise",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="addfranchise",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="addfranchise",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="addfranchise",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")], max_length=20
            ),
        ),
    ]
